CREATE TABLE RESPONSIBLE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER,
	RESPONSIBLE_ID INTEGER,
	CONSTRAINT RESPONSIBLE_FK FOREIGN KEY (RESPONSIBLE_ID) REFERENCES "USER_ACCOUNT"(ID),
	CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES "USER_ACCOUNT"(ID)
);