CREATE TABLE MARK (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ITINERARY_ID INTEGER,
	USER_ID INTEGER,
	LATITUDE REAL,
	LONGITUDE REAL,
	DESCRIPTION TEXT,
	CONSTRAINT MARK_ITINERARY FOREIGN KEY (ITINERARY_ID) REFERENCES "ITINERARY"(ID),
	CONSTRAINT MARK_USER_FK FOREIGN KEY (USER_ID) REFERENCES "USER_ACCOUNT"(ID)
);
