CREATE TABLE ROUTE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ITINERARY_ID INTEGER,
	LATITUDE REAL,
	LONGITUDE REAL,
	CONSTRAINT ROUTE_ITINERARY FOREIGN KEY (ITINERARY_ID) REFERENCES "ITINERARY"(ID)
);

